CREATE TABLE MEMBER(
  MEMBER_NO NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
  ID VARCHAR2(300) CONSTRAINT NN_MEMBER_ID NOT NULL,
  PWD VARCHAR2(300) CONSTRAINT NN_MEMBER_PWD NOT NULL,
  NAME VARCHAR2(300) CONSTRAINT NN_MEMBER_NAME NOT NULL,
  NICK_NAME VARCHAR2(300) CONSTRAINT NN_MEMBER_NICK_NAME NOT NULL
)
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.NICK_NAME IS '별명';

CREATE TABLE STUDENT(
  STUDENT_NO NUMBER CONSTRAINT PK_STUDENTS PRIMARY KEY,
  MEMBER_NO NUMBER CONSTRAINT FK_STUDENTS_MEMBER_NO REFERENCES MEMBER(MEMBER_NO),
  SCHOOL_NAME VARCHAR2 NOT NULL,
  GRADE NUMBER NOT NULL,
  TRACK VARCHAR2(330) NOT NULL,
  TARGET_MAJOR VARCHAR2(330),
  TARGET_UNIV VARCHAR2(330),
  LAST_MOCK_SCORE NUMBER
)
COMMENT ON TABLE STUDENT IS '학생';
COMMENT ON COLUMN STUDENT.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN STUDENT.MEMBER_NO IS '학생 식별번호';
COMMENT ON COLUMN STUDENT.SCHOOL_NAME IS '학교명';
COMMENT ON COLUMN STUDENT.GRADE IS '학년';
COMMENT ON COLUMN STUDENT.TRACK IS '트랙';
COMMENT ON COLUMN STUDENT.TARGET_MAJOR IS '목표 전공';
COMMENT ON COLUMN STUDENT.TARGET_UNIV IS '목표 대학';
COMMENT ON COLUMN STUDENT.LAST_MOCK_SCORE IS '최근 모의고사 점수';

CREATE TABLE STUDENT_RECORD(
  STUDENT_NO NUMBER CONSTRAINT FK_STUDENT_RECORDS_STUDENTS_NO REFERENCES STUDENT(STUDENT_NO),
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(330) NOT NULL,
  ADDRESS VARCHAR2(330) NOT NULL,
  UPLOAD_AT DATE NOT NULL
)
COMMENT ON TABLE STUDENT_RECORD IS '학생기록부';
COMMENT ON COLUMN STUDENT_RECORD.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN STUDENT_RECORD.ORIGINAL_NAME IS '파일 원본 이름';
COMMENT ON COLUMN STUDENT_RECORD.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN STUDENT_RECORD.ADDRESS IS '파일 저장 경로';
COMMENT ON COLUMN STUDENT_RECORD.UPLOAD_AT IS '업로드 시간';

CREATE TABLE CONSULTANT(
  CONSULTANT_NO NUMBER PRIMARY KEY,
  MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO)
)
COMMENT ON TABLE CONSULTANT IS '컨설턴트';
COMMENT ON COLUMN CONSULTANT.CONSULTANT_NO IS '컨설턴트 식별번호';
COMMENT ON COLUMN CONSULTANT.MEMBER_NO IS '회원 식별번호';

CREATE TABLE CONSULTANT_STUDENT(
  CONSULTANT_STUDENT_NO NUMBER PRIMARY KEY,
  CONSULTANT_NO REFERENCES CONSULTANT(CONSULTANT_NO),
  STUDENT_NO REFERENCES STUDENT(STUDENT_NO)
)
COMMENT ON TABLE CONSULTANT_STUDENT IS '컨설턴트-학생';
COMMENT ON COLUMN CONSULTANT_STUDENT.CONSULTANT_STUDENT_NO IS '컨설턴트-학생 식별번호';
COMMENT ON COLUMN CONSULTANT_STUDENT.CONSULTANT_NO IS '컨설턴트 식별번호';
COMMENT ON COLUMN CONSULTANT_STUDENT.STUDENT_NO IS '학생 식별번호';

CREATE TABLE MOCK(
  MOCK_NO NUMBER PRIMARY KEY,
  CONSULTANT_STUDENT_NO REFERENCES CONSULTANT_STUDENT(CONSULTANT_STUDENT_NO),
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(330) NOT NULL,
  ADDRESS VARCHAR2(330) NOT NULL,
  UPLOAD_AT DATE NOT NULL
)
COMMENT ON TABLE MOCK IS '모의고사';
COMMENT ON COLUMN MOCK.MOCK_NO IS '모의고사 식별번호';
COMMENT ON COLUMN MOCK.CONSULTANT_STUDENT_NO IS '컨설턴트-학생 식별번호';
COMMENT ON COLUMN MOCK.ORIGINAL_NAME IS '원본 파일 이름';
COMMENT ON COLUMN MOCK.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN MOCK.ADDRESS IS '파일 경로';
COMMENT ON COLUMN MOCK.UPLOAD_AT IS '업로드 시간';

CREATE TABLE ANALYSIS_RESULT(
  ANALYSIS_RESULT_NO NUMBER PRIMARY KEY,
  CONSULTANT_STUDENT_NO REFERENCES CONSULTANT_STUDENT(CONSULTANT_STUDENT_NO),
  TYPE VARCHAR2(30),
  CREATED_AT DATE
)
