CREATE SEQUENCE SEQ_MEMBER
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_STUDENT
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_MOCK
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_CONSULTANT_STUDENT
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_ANALYSIS_RESULT
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE SEQ_ROLE
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE SEQ_URL_RESOURCE
  SATRT WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;