CREATE TABLE MEMBER(
  MEMBER_NO NUMBER PRIMARY KEY,
  ID VARCHAR2(300) NOT NULL,
  PWD VARCHAR2(300) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  NICKNAME VARCHAR2(300) NOT NULL UNIQUE
);
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.NICKNAME IS '별명';

CREATE TABLE ROLE_INFO(
	ROLE_NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(30) NOT NULL
);
COMMENT ON TABLE ROLE_INFO IS '권한';
COMMENT ON COLUMN ROLE_INFO.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_INFO.NAME IS '이름';

CREATE TABLE MEMBER_ROLE(
	MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO) NOT NULL,
	ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO) NOT NULL
);
COMMENT ON TABLE MEMBER_ROLE IS '회원-권한';
COMMENT ON COLUMN MEMBER_ROLE.MEMBER_NO IS '회원 식별번호';
COMMENT ON COLUMN MEMBER_ROLE.ROLE_NO IS '권한 식별번호';

CREATE TABLE URL_RESOURCE(
	RESOURCE_NO NUMBER PRIMARY KEY,
	PATTERN VARCHAR2(50) NOT NULL,
	HTTP_METHOD VARCHAR2(10) NOT NULL
);
COMMENT ON TABLE URL_RESOURCE IS 'URL자원';
COMMENT ON COLUMN URL_RESOURCE.RESOURCE_NO IS 'URL 식별번호';
COMMENT ON COLUMN URL_RESOURCE.PATTERN IS 'URL패턴';
COMMENT ON COLUMN URL_RESOURCE.HTTP_METHOD IS 'HTTP 메서드'

CREATE TABLE ROLE_URL(
	ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO) NOT NULL,
	RESOURCE_NO NUMBER REFERENCES URL_RESOURCE(RESOURCE_NO) NOT NULL
);
COMMENT ON TABLE ROLE_URL IS '권한-URL';
COMMENT ON COLUMN ROLE_URL.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_URL.RESOURCE_NO IS '자원 식별번호';

CREATE TABLE CONSULTANT(
  CONSULTANT_NO NUMBER PRIMARY KEY,
  MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO) NOT NULL
);
COMMENT ON TABLE CONSULTANT IS '컨설턴트';
COMMENT ON COLUMN CONSULTANT.CONSULTANT_NO IS '컨설턴트 식별번호';
COMMENT ON COLUMN CONSULTANT.MEMBER_NO IS '회원 식별번호';

CREATE TABLE SCHOOL(
	SCHOOL_CODE NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
  SIDO VARCHAR2(70) NOT NULL,
  SIGUNGU VARCHAR2(70),
	COEDUCATION VARCHAR2(10),
	SPECIALIZED VARCHAR2(33),
  SPECIALIZED_TYPE VARCHAR2(70)
);
COMMENT ON TABLE SCHOOL IS '고등학교';
COMMENT ON COLUMN SCHOOL.SCHOOL_CODE IS '학교 행정표준코드';
COMMENT ON COLUMN SCHOOL.NAME IS '이름';
COMMENT ON COLUMN SCHOOL.SIDO IS '시/도';
COMMENT ON COLUMN SCHOOL.SIGUNGU IS '시/군/구';
COMMENT ON COLUMN SCHOOL.COEDUCATION IS '남여공학';
COMMENT ON COLUMN SCHOOL.SPECIALIZED IS '전문고';
COMMENT ON COLUMN SCHOOL.SPECIALIZED_TYPE IS '전문고 종류';

CREATE TABLE STUDENT(
  STUDENT_NO NUMBER PRIMARY KEY,
  SCHOOL_CODE NUMBER REFERENCES SCHOOL(SCHOOL_CODE) NOT NULL,
  NAME VARCHAR2(33) NOT NULL,
  GRADE NUMBER NOT NULL,
  SEMESTER NUMBER NOT NULL,
  TRACK VARCHAR2(330)
);
COMMENT ON TABLE STUDENT IS '학생';
COMMENT ON COLUMN STUDENT.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN STUDENT.SCHOOL_CODE IS '학교 행정표준코드';
COMMENT ON COLUMN STUDENT.NAME IS '이름';
COMMENT ON COLUMN STUDENT.GRADE IS '학년';
COMMENT ON COLUMN STUDENT.SEMESTER IS '학기';
COMMENT ON COLUMN STUDENT.TRACK IS '트랙';

CREATE TABLE TARGET_INFO(
  STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO) NOT NULL,
  UNIV VARCHAR2(100) NOT NULL,
  MAJOR VARCHAR2(100) NOT NULL,
  RANKING NUMBER NOT NULL
);
COMMENT ON TABLE TARGET_INFO IS '목표 대학';
COMMENT ON COLUMN TARGET_INFO.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN TARGET_INFO.UNIV IS '목표 대학';
COMMENT ON COLUMN TARGET_INFO.MAJOR IS '목표 전공';
COMMENT ON COLUMN TARGET_INFO.RANKING IS '지망 순서';

CREATE TABLE RECORD_FILE(
  STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO) NOT NULL,
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(330) NOT NULL,
  ADDRESS VARCHAR2(330) NOT NULL,
  UPLOAD_AT DATE NOT NULL
);
COMMENT ON TABLE RECORD_FILE IS '생기부 파일';
COMMENT ON COLUMN RECORD_FILE.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN RECORD_FILE.ORIGINAL_NAME IS '파일 원본 이름';
COMMENT ON COLUMN RECORD_FILE.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN RECORD_FILE.ADDRESS IS '파일 저장 경로';
COMMENT ON COLUMN RECORD_FILE.UPLOAD_AT IS '업로드 시간';

CREATE TABLE RECORD_ANALYSIS(
  STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO) NOT NULL,
  GRADE_STRENGTH_WEAKNESS         CLOB,
  GRADE_IN_DEPTH_ANALYSIS         CLOB,
  LIFE_RECORD_STRENGTH_WEAKNESS   CLOB,
  LIFE_RECORD_DIAGNOSIS_OVERVIEW  CLOB,
  ACADEMIC_ROADMAP                CLOB,
  PROJECT_RECOMMENDATIONS         CLOB,
  CAREER_BOOK_RECOMMENDATIONS     CLOB,
  PARENT_STUDENT_MESSAGE          CLOB,
  CREATED_AT DATE
);
COMMENT ON TABLE RECORD_ANALYSIS IS '생기부 분석 결과';
COMMENT ON COLUMN RECORD_ANALYSIS.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN RECORD_ANALYSIS.GRADE_STRENGTH_WEAKNESS IS '성적 강점 및 약점 요약';
COMMENT ON COLUMN RECORD_ANALYSIS.GRADE_IN_DEPTH_ANALYSIS IS '과목별 성적 심층 분석';
COMMENT ON COLUMN RECORD_ANALYSIS.LIFE_RECORD_STRENGTH_WEAKNESS IS '활동 기록 강점 및 약점';
COMMENT ON COLUMN RECORD_ANALYSIS.LIFE_RECORD_DIAGNOSIS_OVERVIEW IS '종합 진단';
COMMENT ON COLUMN RECORD_ANALYSIS.ACADEMIC_ROADMAP IS '성적 향상 로드맵';
COMMENT ON COLUMN RECORD_ANALYSIS.PROJECT_RECOMMENDATIONS IS '프로젝트 추천';
COMMENT ON COLUMN RECORD_ANALYSIS.CAREER_BOOK_RECOMMENDATIONS IS '도서 추천';
COMMENT ON COLUMN RECORD_ANALYSIS.PARENT_STUDENT_MESSAGE IS '조언';

CREATE TABLE CONSULTANT_STUDENT(
  CONSULTANT_STUDENT_NO NUMBER PRIMARY KEY,
  MEMBER_NO REFERENCES CONSULTANT(CONSULTANT_NO) NOT NULL,
  STUDENT_NO REFERENCES STUDENT(STUDENT_NO) NOT NULL
);
COMMENT ON TABLE CONSULTANT_STUDENT IS '컨설턴트-학생';
COMMENT ON COLUMN CONSULTANT_STUDENT.CONSULTANT_STUDENT_NO IS '컨설턴트-학생 식별번호';
COMMENT ON COLUMN CONSULTANT_STUDENT.CONSULTANT_NO IS '회원 식별번호';
COMMENT ON COLUMN CONSULTANT_STUDENT.STUDENT_NO IS '학생 식별번호';

CREATE TABLE MOCK_FILE(
  MOCK_NO NUMBER PRIMARY KEY,
  STUDENT_NO REFERENCES STUDENT(STUDENT_NO) NOT NULL,
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(330) NOT NULL,
  ADDRESS VARCHAR2(330) NOT NULL,
  UPLOAD_AT DATE NOT NULL
);
COMMENT ON TABLE MOCK_FILE IS '모의고사';
COMMENT ON COLUMN MOCK_FILE.MOCK_NO IS '모의고사 식별번호';
COMMENT ON COLUMN MOCK_FILE.STUDENT_NO IS '컨설턴트-학생 식별번호';
COMMENT ON COLUMN MOCK_FILE.ORIGINAL_NAME IS '원본 파일 이름';
COMMENT ON COLUMN MOCK_FILE.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN MOCK_FILE.ADDRESS IS '파일 경로';
COMMENT ON COLUMN MOCK_FILE.UPLOAD_AT IS '업로드 시간';


CREATE TABLE MEMBER(
  MEMBER_NO NUMBER PRIMARY KEY,
  ID VARCHAR2(300) NOT NULL,
  PWD VARCHAR2(300) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  NICKNAME VARCHAR2(300) NOT NULL
);
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.NICKNAME IS '별명';

CREATE TABLE ROLE_INFO(
	ROLE_NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(30) NOT NULL
);
COMMENT ON TABLE ROLE_INFO IS '권한';
COMMENT ON COLUMN ROLE_INFO.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_INFO.NAME IS '이름';

CREATE TABLE MEMBER_ROLE(
	MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO) NOT NULL,
	ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO) NOT NULL
);
COMMENT ON TABLE MEMBER_ROLE IS '회원-권한';
COMMENT ON COLUMN MEMBER_ROLE.MEMBER_NO IS '회원 식별번호';
COMMENT ON COLUMN MEMBER_ROLE.ROLE_NO IS '권한 식별번호';

CREATE TABLE URL_RESOURCE(
	RESOURCE_NO NUMBER PRIMARY KEY,
	PATTERN VARCHAR2(50) NOT NULL,
	HTTP_METHOD VARCHAR2(10) NOT NULL
);
COMMENT ON TABLE URL_RESOURCE IS 'URL자원';
COMMENT ON COLUMN URL_RESOURCE.RESOURCE_NO IS 'URL 식별번호';
COMMENT ON COLUMN URL_RESOURCE.PATTERN IS 'URL패턴';
COMMENT ON COLUMN URL_RESOURCE.HTTP_METHOD IS 'HTTP 메서드'

CREATE TABLE ROLE_URL(
	ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO) NOT NULL,
	RESOURCE_NO NUMBER REFERENCES URL_RESOURCE(RESOURCE_NO) NOT NULL
);
COMMENT ON TABLE ROLE_URL IS '권한-URL';
COMMENT ON COLUMN ROLE_URL.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_URL.RESOURCE_NO IS '자원 식별번호';

CREATE TABLE CONSULTANT(
  CONSULTANT_NO NUMBER PRIMARY KEY,
  MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO) NOT NULL
);
COMMENT ON TABLE CONSULTANT IS '컨설턴트';
COMMENT ON COLUMN CONSULTANT.CONSULTANT_NO IS '컨설턴트 식별번호';
COMMENT ON COLUMN CONSULTANT.MEMBER_NO IS '회원 식별번호';

CREATE TABLE SCHOOL(
	SCHOOL_CODE NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
  SIDO VARCHAR2(70) NOT NULL,
  SIGUNGU VARCHAR2(70),
	COEDUCATION VARCHAR2(10),
	SPECIALIZED VARCHAR2(33),
  SPECIALIZED_TYPE VARCHAR2(70)
);
COMMENT ON TABLE SCHOOL IS '고등학교';
COMMENT ON COLUMN SCHOOL.SCHOOL_CODE IS '학교 행정표준코드';
COMMENT ON COLUMN SCHOOL.NAME IS '이름';
COMMENT ON COLUMN SCHOOL.SIDO IS '시/도';
COMMENT ON COLUMN SCHOOL.SIGUNGU IS '시/군/구';
COMMENT ON COLUMN SCHOOL.COEDUCATION IS '남여공학';
COMMENT ON COLUMN SCHOOL.SPECIALIZED IS '전문고';
COMMENT ON COLUMN SCHOOL.SPECIALIZED_TYPE IS '전문고 종류';

CREATE TABLE STUDENT(
  STUDENT_NO NUMBER PRIMARY KEY,
  SCHOOL_CODE NUMBER REFERENCES SCHOOL(SCHOOL_CODE) NOT NULL,
  NAME VARCHAR2(33) NOT NULL,
  GRADE NUMBER NOT NULL,
  SEMESTER NUMBER NOT NULL,
  TRACK VARCHAR2(330)
);
COMMENT ON TABLE STUDENT IS '학생';
COMMENT ON COLUMN STUDENT.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN STUDENT.SCHOOL_CODE IS '학교 행정표준코드';
COMMENT ON COLUMN STUDENT.NAME IS '이름';
COMMENT ON COLUMN STUDENT.GRADE IS '학년';
COMMENT ON COLUMN STUDENT.SEMESTER IS '학기';
COMMENT ON COLUMN STUDENT.TRACK IS '트랙';

CREATE TABLE TARGET_INFO(
  STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO) NOT NULL,
  UNIV VARCHAR2(100) NOT NULL,
  MAJOR VARCHAR2(100) NOT NULL,
  RANKING NUMBER NOT NULL
);
COMMENT ON TABLE TARGET_INFO IS '목표 대학';
COMMENT ON COLUMN TARGET_INFO.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN TARGET_INFO.UNIV IS '목표 대학';
COMMENT ON COLUMN TARGET_INFO.MAJOR IS '목표 전공';
COMMENT ON COLUMN TARGET_INFO.RANKING IS '지망 순서';

CREATE TABLE RECORD_FILE(
  STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO) NOT NULL,
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(330) NOT NULL,
  ADDRESS VARCHAR2(330) NOT NULL,
  UPLOAD_AT DATE DEFAULT SYSDATE
);
COMMENT ON TABLE RECORD_FILE IS '생기부 파일';
COMMENT ON COLUMN RECORD_FILE.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN RECORD_FILE.ORIGINAL_NAME IS '파일 원본 이름';
COMMENT ON COLUMN RECORD_FILE.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN RECORD_FILE.ADDRESS IS '파일 저장 경로';
COMMENT ON COLUMN RECORD_FILE.UPLOAD_AT IS '업로드 시간';

CREATE TABLE RECORD_ANALYSIS(
  STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO) NOT NULL,
  GRADE_STRENGTH_WEAKNESS         CLOB,
  GRADE_IN_DEPTH_ANALYSIS         CLOB,
  LIFE_RECORD_STRENGTH_WEAKNESS   CLOB,
  LIFE_RECORD_DIAGNOSIS_OVERVIEW  CLOB,
  ACADEMIC_ROADMAP                CLOB,
  PROJECT_RECOMMENDATIONS         CLOB,
  CAREER_BOOK_RECOMMENDATIONS     CLOB,
  PARENT_STUDENT_MESSAGE          CLOB,
  CREATED_AT DATE DEFAULT SYSDATE
);
COMMENT ON TABLE RECORD_ANALYSIS IS '생기부 분석 결과';
COMMENT ON COLUMN RECORD_ANALYSIS.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN RECORD_ANALYSIS.GRADE_STRENGTH_WEAKNESS IS '성적 강점 및 약점 요약';
COMMENT ON COLUMN RECORD_ANALYSIS.GRADE_IN_DEPTH_ANALYSIS IS '과목별 성적 심층 분석';
COMMENT ON COLUMN RECORD_ANALYSIS.LIFE_RECORD_STRENGTH_WEAKNESS IS '활동 기록 강점 및 약점';
COMMENT ON COLUMN RECORD_ANALYSIS.LIFE_RECORD_DIAGNOSIS_OVERVIEW IS '종합 진단';
COMMENT ON COLUMN RECORD_ANALYSIS.ACADEMIC_ROADMAP IS '성적 향상 로드맵';
COMMENT ON COLUMN RECORD_ANALYSIS.PROJECT_RECOMMENDATIONS IS '프로젝트 추천';
COMMENT ON COLUMN RECORD_ANALYSIS.CAREER_BOOK_RECOMMENDATIONS IS '도서 추천';
COMMENT ON COLUMN RECORD_ANALYSIS.PARENT_STUDENT_MESSAGE IS '조언';
COMMENT ON COLUMN RECORD_ANALYSIS.CREATED_AT IS '생성 시간';

CREATE TABLE CONSULTANT_STUDENT(
  CONSULTANT_STUDENT_NO NUMBER PRIMARY KEY,
  MEMBER_NO REFERENCES CONSULTANT(CONSULTANT_NO) NOT NULL,
  STUDENT_NO REFERENCES STUDENT(STUDENT_NO) NOT NULL
);
COMMENT ON TABLE CONSULTANT_STUDENT IS '컨설턴트-학생';
COMMENT ON COLUMN CONSULTANT_STUDENT.CONSULTANT_STUDENT_NO IS '컨설턴트-학생 식별번호';
COMMENT ON COLUMN CONSULTANT_STUDENT.CONSULTANT_NO IS '회원 식별번호';
COMMENT ON COLUMN CONSULTANT_STUDENT.STUDENT_NO IS '학생 식별번호';

CREATE TABLE MOCK_FILE(
  MOCK_NO NUMBER PRIMARY KEY,
  STUDENT_NO REFERENCES STUDENT(STUDENT_NO) NOT NULL,
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(330) NOT NULL,
  ADDRESS VARCHAR2(330) NOT NULL,
  UPLOAD_AT DATE DEFAULT SYSDATE
);
COMMENT ON TABLE MOCK_FILE IS '모의고사';
COMMENT ON COLUMN MOCK_FILE.MOCK_NO IS '모의고사 식별번호';
COMMENT ON COLUMN MOCK_FILE.STUDENT_NO IS '컨설턴트-학생 식별번호';
COMMENT ON COLUMN MOCK_FILE.ORIGINAL_NAME IS '원본 파일 이름';
COMMENT ON COLUMN MOCK_FILE.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN MOCK_FILE.ADDRESS IS '파일 경로';
COMMENT ON COLUMN MOCK_FILE.UPLOAD_AT IS '업로드 시간';

CREATE TABLE ASYNC_STATUS(
  ASYNC_NO NUMBER PRIMARY KEY,
  JOB_ID_NO NUMBER,
  TYPE VARCHAR2(30),
  STARTED_AT DATE DEFAULT SYSDATE,
  COMPLETED_AT DATE,
  STATUS VARCHAR2(10)
);
COMMENT ON TABLE ASYNC_STATUS IS '비동기 요청 작업 상태값';
COMMENT ON COLUMN ASYNC_STATUS.ASYNC_NO IS '작업 식별번호';
COMMENT ON COLUMN ASYNC_STATUS.JOB_ID_NO IS '작업 대상 식별번호';
COMMENT ON COLUMN ASYNC_STATUS.TYPE IS '작업 종류';
COMMENT ON COLUMN ASYNC_STATUS.STARTED_AT IS '시작 시간';
COMMENT ON COLUMN ASYNC_STATUS.COMPLETED_AT IS '종료 시간';
COMMENT ON COLUMN ASYNC_STATUS.STATUS IS '상태값';