CREATE TABLE MEMBER(
  MEMBER_NO NUMBER PRIMARY KEY,
  ID VARCHAR2(300) NOT NULL,
  PWD VARCHAR2(300) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  NICKNAME VARCHAR2(300) NOT NULL
);
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.NICKNAME IS '별명';

CREATE TABLE ROLE_INFO(
	ROLE_NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(30) NOT NULL
);
COMMENT ON TABLE ROLE_INFO IS '권한';
COMMENT ON COLUMN ROLE_INFO.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_INFO.NAME IS '이름';

CREATE TABLE MEMBER_ROLE(
	MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO),
	ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO)
);
COMMENT ON TABLE MEMBER_ROLE IS '회원-권한';
COMMENT ON COLUMN MEMBER_ROLE.MEMBER_NO IS '회원 식별번호';
COMMENT ON COLUMN MEMBER_ROLE.ROLE_NO IS '권한 식별번호';

CREATE TABLE URL_RESOURCE(
	RESOURCE_NO NUMBER PRIMARY KEY,
	PATTERN VARCHAR2(50) NOT NULL,
	HTTP_METHOD VARCHAR2(10) NOT NULL
);
COMMENT ON TABLE URL_RESOURCE IS 'URL자원';
COMMENT ON COLUMN URL_RESOURCE.RESOURCE_NO IS 'URL 식별번호';
COMMENT ON COLUMN URL_RESOURCE.PATTERN IS 'URL패턴';
COMMENT ON COLUMN URL_RESOURCE.HTTP_METHOD IS 'HTTP 메서드'

CREATE TABLE ROLE_URL(
	ROLE_NO NUMBER REFERENCES ROLE_INFO(ROLE_NO),
	RESOURCE_NO NUMBER REFERENCES URL_RESOURCE(RESOURCE_NO)
);
COMMENT ON TABLE ROLE_URL IS '권한-URL';
COMMENT ON COLUMN ROLE_URL.ROLE_NO IS '권한 식별번호';
COMMENT ON COLUMN ROLE_URL.RESOURCE_NO IS '자원 식별번호';

CREATE TABLE CONSULTANT(
  CONSULTANT_NO NUMBER PRIMARY KEY,
  MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO)
);
COMMENT ON TABLE CONSULTANT IS '컨설턴트';
COMMENT ON COLUMN CONSULTANT.CONSULTANT_NO IS '컨설턴트 식별번호';
COMMENT ON COLUMN CONSULTANT.MEMBER_NO IS '회원 식별번호';

CREATE TABLE HIGH_SCHOOL(
	HIGH_SCHOOL_CODE NUMBER PRIMARY KEY,
	NAME VARCHAR2(330) NOT NULL,
	PROVINCE VARCHAR2(330) NOT NULL,
	COEDUCATION VARCHAR2(15) NOT NULL,
	SPECIALIZED VARCHAR2(20)
);
COMMENT ON TABLE HIGH_SCHOOL IS '고등학교';
COMMENT ON COLUMN HIGH_SCHOOL.HIGH_SCHOOL_CODE IS '학교 행정표준코드';
COMMENT ON COLUMN HIGH_SCHOOL.NAME IS '이름';
COMMENT ON COLUMN HIGH_SCHOOL.PROVINCE IS '지역';
COMMENT ON COLUMN HIGH_SCHOOL.COEDUCATION IS '남여공학';
COMMENT ON COLUMN HIGH_SCHOOL.SPECIALIZED IS '전문고';

CREATE TABLE STUDENT(
  STUDENT_NO NUMBER PRIMARY KEY,
  HIGH_SCHOOL_CODE NUMBER REFERENCES HIGH_SCHOOL(HIGH_SCHOOL_CODE),
  GRADE NUMBER,
  TRACK VARCHAR2(330),
  TARGET_MAJOR VARCHAR2(330),
  TARGET_UNIV VARCHAR2(330)
);
COMMENT ON TABLE STUDENT IS '학생';
COMMENT ON COLUMN STUDENT.HIGH_SCHOOL_CODE IS '학교 행정표준코드';
COMMENT ON COLUMN STUDENT.SCHOOL_NAME IS '학교명';
COMMENT ON COLUMN STUDENT.GRADE IS '학년';
COMMENT ON COLUMN STUDENT.TRACK IS '트랙';
COMMENT ON COLUMN STUDENT.TARGET_MAJOR IS '목표 전공';
COMMENT ON COLUMN STUDENT.TARGET_UNIV IS '목표 대학';


CREATE TABLE STUDENT_RECORD(
  STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO),
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(330) NOT NULL,
  ADDRESS VARCHAR2(330) NOT NULL,
  UPLOAD_AT DATE NOT NULL
);
COMMENT ON TABLE STUDENT_RECORD IS '학생기록부';
COMMENT ON COLUMN STUDENT_RECORD.STUDENT_NO IS '학생 식별번호';
COMMENT ON COLUMN STUDENT_RECORD.ORIGINAL_NAME IS '파일 원본 이름';
COMMENT ON COLUMN STUDENT_RECORD.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN STUDENT_RECORD.ADDRESS IS '파일 저장 경로';
COMMENT ON COLUMN STUDENT_RECORD.UPLOAD_AT IS '업로드 시간';

CREATE TABLE CONSULTANT_STUDENT(
  CONSULTANT_STUDENT_NO NUMBER PRIMARY KEY,
  MEMBER_NO REFERENCES CONSULTANT(CONSULTANT_NO),
  STUDENT_NO REFERENCES STUDENT(STUDENT_NO)
);
COMMENT ON TABLE CONSULTANT_STUDENT IS '컨설턴트-학생';
COMMENT ON COLUMN CONSULTANT_STUDENT.CONSULTANT_STUDENT_NO IS '컨설턴트-학생 식별번호';
COMMENT ON COLUMN CONSULTANT_STUDENT.CONSULTANT_NO IS '회원 식별번호';
COMMENT ON COLUMN CONSULTANT_STUDENT.STUDENT_NO IS '학생 식별번호';

CREATE TABLE MOCK(
  MOCK_NO NUMBER PRIMARY KEY,
  CONSULTANT_STUDENT_NO REFERENCES CONSULTANT_STUDENT(CONSULTANT_STUDENT_NO),
  ORIGINAL_NAME VARCHAR2(330) NOT NULL,
  CHANGED_NAME VARCHAR2(330) NOT NULL,
  ADDRESS VARCHAR2(330) NOT NULL,
  UPLOAD_AT DATE NOT NULL
);
COMMENT ON TABLE MOCK IS '모의고사';
COMMENT ON COLUMN MOCK.MOCK_NO IS '모의고사 식별번호';
COMMENT ON COLUMN MOCK.CONSULTANT_STUDENT_NO IS '컨설턴트-학생 식별번호';
COMMENT ON COLUMN MOCK.ORIGINAL_NAME IS '원본 파일 이름';
COMMENT ON COLUMN MOCK.CHANGED_NAME IS '변경된 이름';
COMMENT ON COLUMN MOCK.ADDRESS IS '파일 경로';
COMMENT ON COLUMN MOCK.UPLOAD_AT IS '업로드 시간';

CREATE TABLE ANALYSIS_RESULT(
  ANALYSIS_RESULT_NO NUMBER PRIMARY KEY,
  CONSULTANT_STUDENT_NO REFERENCES CONSULTANT_STUDENT(CONSULTANT_STUDENT_NO),
  TYPE VARCHAR2(30),
  CREATED_AT DATE
);

