-- MEMBER추가하면 MEMBER-ROLES테이블에 권한 추가하기
CREATE OR REPLACE TRIGGER TRG_NEW_MEMBER
AFTER INSERT ON MEMBER
FOR EACH ROW
DECLARE
  V_ROLE_NO ROLE_INFO.ROLE_NO%TYPE;
BEGIN
  SELECT ROLE_NO
  INTO V_ROLE_NO
  FROM ROLE_INFO
  WHERE NAME = 'ROLE_VIEWER';

  INSERT INTO MEMBER_ROLE (MEMBER_NO, ROLE_NO)
  VALUES (:NEW.MEMBER_NO, V_ROLE_NO);
END;
/

-- CONSULTANT권한 추가 시 CONSULTANT테이블에 추가
-- CONSULTANT_LEADER권한 추가 시 CONSULTANT권한을 부여하고, CONSULTANT테이블에 추가
CREATE OR REPLACE TRIGGER TRG_NEW_CONSULTANT
AFTER INSERT ON MEMBER_ROLE
FOR EACH ROW
DECLARE
  V_NEW_ROLE_NAME  ROLE_INFO.NAME%TYPE;
  V_VIEWER_ROLE_NO ROLE_INFO.ROLE_NO%TYPE;
BEGIN
  SELECT NAME INTO V_NEW_ROLE_NAME
  FROM ROLE_INFO
  WHERE ROLE_NO = :NEW.ROLE_NO;

  IF V_NEW_ROLE_NAME = 'ROLE_CONSULTANT_LEADER' THEN
    SELECT ROLE_NO INTO V_VIEWER_ROLE_NO
    FROM ROLE_INFO
    WHERE NAME = 'ROLE_CONSULTANT';

    INSERT INTO MEMBER_ROLE (MEMBER_NO, ROLE_NO)
    SELECT :NEW.MEMBER_NO, V_VIEWER_ROLE_NO FROM DUAL
    WHERE NOT EXISTS (
      SELECT 1 FROM MEMBER_ROLE
      WHERE MEMBER_NO = :NEW.MEMBER_NO
      AND ROLE_NO = V_VIEWER_ROLE_NO
    );
  END IF;

  IF V_NEW_ROLE_NAME IN ('ROLE_CONSULTANT', 'ROLE_CONSULTANT_LEADER') THEN
    INSERT INTO CONSULTANT (CONSULTANT_NO)
    SELECT :NEW.MEMBER_NO FROM DUAL
    WHERE NOT EXISTS (
      SELECT 1 FROM CONSULTANT
      WHERE CONSULTANT_NO = :NEW.MEMBER_NO
    );
  END IF;
END;
/