INSERT ALL
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (1, 'ROLE_ADMIN')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (2, 'ROLE_CONSULTANT')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (3, 'ROLE_STUDENT')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (4, 'ROLE_VIEWER')

  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (1, '성적 강점 및 약점 요약')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (2, '과목별 성적 심층 분석')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (3, '활동 기록 강점 및 약점')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (4, '종합 진단')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (5, '성적 향상 로드맵')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (6, '프로젝트 추천')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (7, '도서 추천')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (8, '조언')

SELECT * FROM DUAL;

COMMIT;