INSERT ALL
  -- 권한 테이블 채우기
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (1, 'ROLE_SUPER_ADMIN')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (2, 'ROLE_ADMIN')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (3, 'ROLE_CONSULTANT')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (4, 'ROLE_STUDENT')
  INTO ROLE_INFO (ROLE_NO, NAME) VALUES (5, 'ROLE_VIEWER')

  -- 분석 항목 채우기
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (1, '성적 강점 및 약점 요약')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (2, '과목별 성적 심층 분석')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (3, '활동 기록 강점 및 약점')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (4, '종합 진단')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (5, '성적 향상 로드맵')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (6, '프로젝트 추천')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (7, '도서 추천')
  INTO ANALYSIS_ITEM (ITEM_NO, FIELD) VALUES (8, '조언')

  -- 최고 관리자 생성
  INTO MEMBER(ID, PWD, NAME, NICKNAME) VALUES ('asdf', '$2a$10$Zx4kOtUhOiT69iX7ZkwcFeO1OKKMiDjhtsgDgVxEqjibMh3HwnV06', '최고 관리자', '최고 관리자')
SELECT * FROM DUAL;


-- 최고 관리자 권한 수정
UPDATE MEMBER_ROLE
SET ROLE_NO = 1
WHERE MEMBER_NO = 1;


-- 최고 관리자 권한 추가
INSERT ALL
  INTO MEMBER_ROLE(MEMBER_NO, ROLE_NO) VALUES(1,2)
SELECT * FROM DUAL;

COMMIT;